### ISSUE TITLE
Weird messages with StatsPlots.jl

### ISSUE THREAD

**Issue by aerdely** [fonsp/Pluto.jl#1870] opened 2022-01-29 21:02 UTC
1. Video: 

https://user-images.githubusercontent.com/3356159/151677426-301eb128-936b-4888-aad7-e2e33fc35360.mp4

2. Pluto notebook file: [violin.jl](https://gist.github.com/aerdely/fc1261037eac9ef83f1f97565818bcab)

**Comment by fonsp** [comment] 2022-01-30 22:36
Thanks! The are warning logs sent by StatsPlots, (Pluto recently started displaying logs). Can you also report this to StatsPlots.jl?

**Comment by aerdely** [comment] 2022-01-31 01:38
Sure! Thanks.

**Comment by sethaxen** [comment] 2022-01-31 02:28
The warning about `violin` moving to StatsPlots is being trigged here because this condition evaluates to `false`:
https://github.com/JuliaPlots/Plots.jl/blob/2896c5a25a40d72c635dd60b307fe1446ec70c2f/src/args.jl#L1578
That is, StatsPlots does not appear to be in the `Main` namespace when loaded in Pluto. @fonsp, is this expected behavior?

**Comment by fonsp** [comment] 2022-02-01 14:45
Thanks for debugging! This is expected, we don't evaluate user code in `Main` because we manage the scope.

Plots should probably use `Base.loaded_modules` instead, e.g.
```julia
haskey(
	Base.loaded_modules, 
	Base.PkgId(
		Base.UUID("3fa0cd96-eef1-5676-8a61-b3b8758bbffb"), 
		"REPL"
	)
)
```

**Comment by fonsp** [comment] 2022-02-05 11:42
Can someone make a PR to Plots.jl to solve this? 💖

**Comment by sethaxen** [comment] 2022-02-05 13:19
I found it's a duplicate of https://github.com/JuliaPlots/Plots.jl/issues/3746, where a solution was previously started on but unfinished, so let's continue the discussion there.

**Closed** 2022-02-05 16:06 UTC
Labels: good first issue, other packages
