### ISSUE TITLE
No method matching shouldlog world age error

### ISSUE THREAD

**Issue by GiggleLiu** [fonsp/Pluto.jl#695] opened 2020-11-19 04:30 UTC
Pluto v0.12.10, Ubuntu 20.04

Every time I open the notebook, it shows the following message. I need to trigger the execution manualy to make it not error. It looks like a world age problem. Is it because I put Pluto in the package dependency?

```julia
MethodError: no method matching shouldlog(::Pluto.PlutoRunner.PlutoLogger, ::Base.CoreLogging.LogLevel, ::Module, ::Symbol, ::Symbol)

The applicable method may be too new: running in world age 27979, while current world is 28028.

Closest candidates are:

shouldlog(::Pluto.PlutoRunner.PlutoLogger, ::Any, ::Any, ::Any...) at /home/leo/.julia/packages/Pluto/SseIQ/src/runner/PlutoRunner.jl:807 (method too new to be called from this world context.)

shouldlog(!Matched::Base.CoreLogging.NullLogger, ::Any...) at logging.jl:93

shouldlog(!Matched::Base.CoreLogging.SimpleLogger, ::Any, ::Any, ::Any, ::Any) at logging.jl:540

...

_invoked_shouldlog@logging.jl:78[inlined]
macro expansion@logging.jl:327[inlined]
stale_cachefile(::String, ::String)@loading.jl:1448
_require_search_from_serialized(::Base.PkgId, ::String)@loading.jl:758
_tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::Nothing)@loading.jl:712
_require_from_serialized(::String)@loading.jl:744
_require(::Base.PkgId)@loading.jl:1040
require(::Base.PkgId)@loading.jl:928
require(::Module, ::Symbol)@loading.jl:923
top-level scope
```

**Comment by GiggleLiu** [comment] 2020-11-19 04:43
Bingo, it does not error anymore if I use Requires to specify the Pluto dependency in the package.

Sorry for trying stupid thing and triggering stupid errors :P. Do you want to fix this issue? Feel free to close it @fonsp

**Comment by fonsp** [comment] 2020-11-19 13:29
Do you think that someone else will find this problem?

**Comment by GiggleLiu** [comment] 2020-11-19 21:43
Just do the experiment, if a second people find it, he will probably find this issue and comment here. So I suggest open this issue for a while, so that people find it easier.

It should be good to close this issue like after June 1st, 2021.

**Comment by galran** [comment] 2021-03-22 22:31
well, another user encountered this message :) 
I added Pluto to one of the packages I'm developing when I try to use that package inside a notebook I'm getting the following error:

MethodError: no method matching shouldlog(::Pluto.PlutoRunner.PlutoLogger, ::Base.CoreLogging.LogLevel, ::Module, ::Symbol, ::Symbol)

The applicable method may be too new: running in world age 28007, while current world is 28278.

Closest candidates are:

shouldlog(::Pluto.PlutoRunner.PlutoLogger, ::Any, ::Any, ::Any...) at C:\Users\rgal\.julia\packages\Pluto\uSLhP\src\runner\PlutoRunner.jl:1164 (method too new to be called from this world context.)

shouldlog(!Matched::Base.CoreLogging.NullLogger, ::Any...) at logging.jl:93

shouldlog(!Matched::Base.CoreLogging.SimpleLogger, ::Any, ::Any, ::Any, ::Any) at logging.jl:540

...

_invoked_shouldlog@logging.jl:78[inlined]
macro expansion@logging.jl:327[inlined]
stale_cachefile(::String, ::String)@loading.jl:1448
_require_search_from_serialized(::Base.PkgId, ::String)@loading.jl:758
_tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String)@loading.jl:712
_require_search_from_serialized(::Base.PkgId, ::String)@loading.jl:771
_require(::Base.PkgId)@loading.jl:1007
require(::Base.PkgId)@loading.jl:928
require(::Module, ::Symbol)@loading.jl:923
top-level scope@Local: 2


any ideas?

**Comment by fonsp** [comment] 2021-04-13 16:07
I suspect that this has been fixed by https://github.com/fonsp/Pluto.jl/commit/5b22f9bf207c3a1479dae4058e4da1eeffec28de

**Comment by galran** [comment] 2021-04-13 16:53
thanks. i currently just solved it using an @eval around the code. it seems that the "using Pluto" is the part that is causing the problem. when i use @eval to delay it everything seems to be working well. all i'm using it for is to allow an easier launching of Pluto with a specific notebook.

**Comment by fonsp** [comment] 2021-05-04 20:16
@galran Can you check that the problem is fixed?

**Comment by fonsp** [comment] 2021-05-04 20:31
I can't reproduce it, importing Pluto inside Pluto and then logging works fine.

**Closed by fonsp** 2021-05-04 20:31 UTC
Labels: display & PlutoRunner

**Comment by galran** [comment] 2021-05-04 22:48
yeah, seems to be working fine now.
thanks!
