### ISSUE TITLE
Editing breaks Pluto

### ISSUE THREAD

**Issue by dojt** [fonsp/Pluto.jl#490] opened 2020-09-25 08:19 UTC
Consider the 3-cell Pluto notebook below .
1. Start Julia, using Pluto, run Pluto
2. In Pluto: New Notebook; copy-paste the 3 cells -- everything runs fine
3. Move cursor to the position in the following screenshot, after the `(` before the `m`
![image](https://user-images.githubusercontent.com/57910358/94241887-f05d4400-ff1d-11ea-9e52-83ca228535ac.png)
4. Hit backspace once
5. Type `{` (fails)

At that time the cursor disappears, and the `{` is not shown, further characters are swallowed, too. Arrow keys (to move cursor) are not ignored, but have funny effects, e.g., can move the cursor to between two lines:
![image](https://user-images.githubusercontent.com/57910358/94240964-b17abe80-ff1c-11ea-9f3c-6325b724f655.png)

If you cannot reproduce it, it might be a browser/OS issue...?
* Pluto.jl v0.11.14
* Julia v1.5.1
* Google Chrome, version 85.0.4183.108 (Official Build) (64-bit)
* on Chrome OS
* Julia runs in Linux VM (Debian buster)

### Pluto Notebook
Cell 1
```Julia
begin
	const ℂ = ComplexF64
	struct 𝕄{m,n}   # \bbM
		a ::NTuple{m,NTuple{n,ℂ}}
	
		function 𝕄{m,n}(value_fn::Function) where m where n
			new( ntuple( k -> ntuple(ℓ->convert(ℂ,value_fn(k,ℓ)),n), m) ) # \ell
		end
	end
	
	𝕄(m::Int,n::Int,ζ ::Real)  = 𝕄{m,n}( (k,ℓ) -> ζ )
	
	import Base: getindex
	function getindex(A ::𝕄{m,n}, k::Int,ℓ::Int) ::ℂ  where m where n
		@assert 1 ≤ k ≤ m
		@assert 1 ≤ ℓ ≤ n
		A.a[k][ℓ]
	end
end ;
```
Cell 2
```Julia
𝟎 = 𝕄(2,3, 0)
```
Cell 3
```Julia
𝟎[1,1]
```

**Comment by Pocket-titan** [comment] 2020-09-25 12:32
Reproduced:
![editing_bug](https://user-images.githubusercontent.com/4435990/94267284-9a979480-ff3b-11ea-98ad-d08d3109e22c.gif)

The chrome console repeatedly logs the following error:
![error](https://user-images.githubusercontent.com/4435990/94266961-19400200-ff3b-11ea-9dba-52dbe5edd8f2.jpg)

Which reveals line 258 in the `codemirror` mode `julia.js` to be the culprit:
```js
var match = stream.match(/^(\(\s*)/);
```

But I don't immediately see an easy solution. Since this is an issue with codemirror, maybe we can close this and open an issue there?

**Comment by fonsp** [comment] 2020-09-25 14:17
Can you post this as an issue to CodeMirror?

MWE:
```julia
a(){}()
```

Delete first `(` using backspace and then type `{`. Mention that this happens in the standalone demo:
https://codemirror.net/mode/julia/
(ie it's unrelated to Pluto)

**Comment by dojt** [comment] 2020-09-26 06:09
@Pocket-titan, @fonsp, @RomansWorks: 
Could one of you be so kind to post the issue on CodeMirror, https://github.com/codemirror/CodeMirror/issues, as Fons suggested?
I never even heard of CodeMirror before just now, so I wouldn't know where to begin.... :-\

**Comment by RomansWorks** [comment] 2020-09-26 11:27
Opened https://github.com/codemirror/CodeMirror/issues/6428 :)

**Closed** 2020-09-26 12:37 UTC
