### ISSUE TITLE
IOError when opening a new Pluto nb

### ISSUE THREAD

**Issue by SimonEnsemble** [fonsp/Pluto.jl#578] opened 2020-10-16 03:22 UTC
my student gets an `IOError` when opening a new Pluto notebook. the main Pluto page launches, but when he clicks to open a new notebook, he just sees a white page, and the error below appears in the REPL.

OS: Windows
Julia: 1.5.2
Pluto: v0.12.4
browser: happens in Chrome and Firefox

![image](https://user-images.githubusercontent.com/30643894/96209275-0e6a0300-0f24-11eb-8261-5fbfc71110f8.png)

```
opening http://localhost:1234/?secret=AK51B4DQ in your default browser... ~ have fun!                                                                                                                                                           Press Ctrl+C in this terminal to stop Pluto                                                                                                                                                                                                     ┌ Warning: Reading WebSocket client stream failed for unknown reason:                                                   │   exception =                                                                                                         │    IOError: read: connection reset by peer (ECONNRESET)                                                               │    Stacktrace:                                                                                                        │     [1] wait_readnb(::Sockets.TCPSocket, ::Int64) at .\stream.jl:350                                                  │     [2] eof at .\stream.jl:48 [inlined]                                                                               │     [3] eof(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}) at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\ConnectionPool.jl:199                                                                                                      │     [4] eof at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\WebSockets.jl:251 [inlined]                              │     [5] (::Pluto.var"#208#215"{Pluto.ServerSession,Base.RefValue{Function}})(::HTTP.WebSockets.WebSocket{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at C:\Users\akifm\.julia\packages\Pluto\2pyPe\src\webserver\WebServer.jl:139    │     [6] upgrade(::Pluto.var"#208#215"{Pluto.ServerSession,Base.RefValue{Function}}, ::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}; binary::Bool) at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\WebSockets.jl:160                                                                                                 │     [7] upgrade at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\WebSockets.jl:142 [inlined]                          │     [8] (::Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}})(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at C:\Users\akifm\.julia\packages\Pluto\2pyPe\src\webserver\WebServer.jl:134                                                                      │     [9] handle at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\Handlers.jl:269 [inlined]                             │     [10] #4 at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\Handlers.jl:345 [inlined]                                │     [11] macro expansion at C:\Users\akifm\.julia\packages\HTTP\IAI92\src\Servers.jl:367 [inlined]                    │     [12] (::HTTP.Servers.var"#13#14"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}},HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}})() at .\task.jl:356                                                                                                               └ @ Pluto C:\Users\akifm\.julia\packages\Pluto\2pyPe\src\webserver\WebServer.jl:180                                     ┌ Error: (Base.IOError("read: connection reset by peer (ECONNRESET)", -4077), Base.StackTraces.StackFrame[wait_readnb(::Sockets.TCPSocket, ::Int64) at stream.jl:336, eof at stream.jl:48 [inlined], read_to_buffer(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Int64) at ConnectionPool.jl:251, readuntil(::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::Function, ::Int64) at ConnectionPool.jl:271, readuntil at ConnectionPool.jl:269 [inlined], readheaders at Messages.jl:471 [inlined], startread(::HTTP.Streams.Stream{HTTP.Messages.Request,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}) at Streams.jl:155, handle_transaction(::HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}}, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}; final_transaction::Bool) at Servers.jl:343, (::HTTP.Servers.var"#handle_transaction##kw")(::NamedTuple{(:final_transaction,),Tuple{Bool}}, ::typeof(HTTP.Servers.handle_transaction), ::Function, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}) at Servers.jl:338, handle_connection(::Function, ::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, ::HTTP.Servers.Server{Nothing,Sockets.TCPServer}, ::Int64, ::Int64) at Servers.jl:299, (::HTTP.Servers.var"#8#9"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.StreamHandlerFunction{Pluto.var"#207#214"{Pluto.ServerSession,HTTP.Handlers.Router{Symbol("##253")},Base.RefValue{Function}}}},HTTP.Servers.Server{Nothing,Sockets.TCPServer},Base.RefValue{Int64},Int64,Int64,Bool,HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})() at task.jl:356])                                                  └ @ HTTP.Servers C:\Users\akifm\.julia\packages\HTTP\IAI92\src\Servers.jl:264
```

**Comment by fonsp** [comment] 2020-11-01 16:43
The error message is because of a bug in HTTP.jl, it gets printed sometimes when you navigate away, and is very likely unrelated to the blank page issue.

As for the blank page issue, it sounds like they just need to update the browser. If that didn't help, please follow these steps:
https://github.com/fonsp/Pluto.jl/issues/553

I will close this until we have more info to reproduce the issue

**Closed by fonsp** 2020-11-01 16:43 UTC
