### ISSUE TITLE
Run Cell button disappeared when upgrading from 0.19.11 to 0.19.13

### ISSUE THREAD

**Issue by sindresops** [fonsp/Pluto.jl#2327] opened 2022-10-19 12:50 UTC
Since I upgraded from Pluto.jl v0.19.11 to v0.19.13 the "Run Cell" button has disappeared. I can click in the spot where it is supposed to be and run the cell, but the icon itself is not displayed. Upon pressing the invisible button, the button for "Interrupt cell" pops up. When executing the button again disappears. Video attahced.

https://user-images.githubusercontent.com/29738855/196695070-606ed7f1-cd8d-407a-8c30-3acb390fd6b3.mov

**Comment by disberd** [comment] 2022-10-19 13:19
duplicate of #2313, it was addressed in #2320 so it should be fixed in the next release (v0.19.14)

**Comment by fonsp** [comment] 2022-10-19 17:39
Thanks for the report @sindresops !

**Closed by fonsp** 2022-10-19 17:39 UTC
