### ISSUE TITLE
Macros and DSLs

### ISSUE THREAD

**Issue by zenon** [fonsp/Pluto.jl#196] opened 2020-06-26 20:52 UTC
I try out Soss.jl, a tool for probabilistic programming.

I can't attach .jl files, so I changed them to txt.

This (non Pluto) works fine:
[sosstest01.txt](https://github.com/fonsp/Pluto.jl/files/4839201/sosstest01.txt)

This (Pluto) doesn't:
[sosstest02.txt](https://github.com/fonsp/Pluto.jl/files/4839208/sosstest02.txt)

Error message:
Cyclic references among m, y and forwardModel:
Combine all definitions into a single reactive cell using a `begin ... end` block.

Am I doing sth wrong, or has Pluto an issue with macros?

Kind greetings, z.

**Comment by fonsp** [comment] 2020-06-26 21:39
Pluto doesn't understand macros, it just looks at the code as if the macro wasn't there.

This is a difficult problem: the macro is not known to Pluto - it is only defined inside the notebook process. To understand (i.e. _expand_) macros, there needs to be an analysis step _after_ normal analysis, but _before_ runtime (because the analysis determines which cells will run).

So _Domain Specific Languages_ like Soss.jl might not work well.

**Comment by zenon** [comment] 2020-06-27 06:04
Hello Fons, thank you for the fast answer. 

Hm. I was afraid it would come out this way. :-)

Kind greetings, z.

**Comment by fonsp** [comment] 2020-07-22 22:46
About DSLs: I am thinking that maybe Pluto can include a "mock version" for a bunch of popular packages with DSLs. 

So not the original macro, but a macro that transforms the code into something that has the intended _references_ and _definitions_. For example, Replace=with~.jl could transform
```julia
@replaceit x ~ y + 1
```
(Pluto thinks that `x`, `y` and `+` are the references, with no assignments)
to
```julia
x = y + 1
```

**Comment by fonsp** [comment] 2020-07-22 22:49
Although, looking at this issue again - the problem is not the DSL, it's a bug in Pluto's syntax analysis! #225

**Comment by fonsp** [comment] 2020-07-22 22:59
Your original issue should be fixed now! But the DSL problem is still there

**Comment by zenon** [comment] 2020-08-05 13:53
Yes! It now works (even if I understand that there are no guarantees :-) )

Thank you for the hint.

**Comment by aplavin** [comment] 2020-09-05 22:47
Another important case when this issue happens in with the `Query.jl` package: `df |> @map({a = _.b})` is treated as assigment to `a` by `Pluto`.

**Comment by fonsp** [comment] 2020-09-06 09:23
See a workaround for some macros here: #371

**Comment by fonsp** [comment] 2020-09-08 20:58
Query.jl and VegaLite.jl both use `{a = 1}` to mean something similar to a named tuple, `(a = 1,)` not as an assignment to `a`. `{}` is not part of base Julia syntax, so we can change Pluto to always interpret `{}` that way.

This will fix those two packages, but it might break others. Which other packages use `{}` inside a DSL?

**Comment by mcabbott** [comment] 2020-09-08 22:27
I was wondering how to make things like `@einsum a[i] := b[i,j] * c[j]` work; here `:=` means this assigns to a new array. Like `{a=1}` I don't think this is allowed outside of macros, might this be another candidate case?

**Comment by fonsp** [comment] 2020-09-08 22:29
Yep! But you need to figure out what other packages are affected

**Comment by mcabbott** [comment] 2020-09-08 22:33
Excellent. I know half a dozen who use this notation (some of which I'm guilty of writing) and can't immediately think of other macros using `:=`, but will dig a bit.

**Comment by fonsp** [comment] 2020-09-09 00:38
Although note that `a[1] = 2` counts as a reference to `a` in Pluto, not an assignment to `a`, so in the specific example that you gave, there is no differnce.

**Comment by mcabbott** [comment] 2020-09-09 06:13
Yes, only with `:=` is it assignment. Something like `@einsum a[i] = b[i,j] * c[j]` ought to count as a reference to `a,b,c`, although ideally not to `i,j`.

**Comment by mcabbott** [comment] 2020-09-10 13:01
So under option 3, nothing has to be re-written if you change how `SymbolsState` works. That's certainly better than 2. 

Where should these mock macros / mocking functions live? Just some `MacroZoo` folder inside Pluto?

And should they be a little bit namespaced? Presumably Pluto knows what packages have been loaded, so it might make sense to restrict each rule to notebooks which have loaded its owner, to avoid surprises because of some package you've never heard of.

**Comment by fonsp** [comment] 2020-09-10 13:06
1st Q: Not sure what you mean.

2nd Q: Yes!

3rd !: Oof the namespacing problem is really tough, because you only know which macros are defined by the notebook _after_ you have done the syntax analysis. I say we just ignore this problem

**Comment by mcabbott** [comment] 2020-09-10 13:20
1st -- not important but I think I was just parsing the difference between your 2 & 3. The good thing about 3 is not so much whether you make a mock macro vs. a function, it's that it returns an expression back into the ordinary analysis pipeline, and thus it's independent of Pluto's implementation details.

2nd -- ok! 

3rd -- If I understand right, you are saying the analysis is run on cells independently, and can't expect to be told about what was seen in earlier cells. 

So what's the interface? For each macro, there must be a function which maps expressions to an expression. Perhaps these are `mock_macro(::Val{:pipe}, exs...)`? But if you call `Pipe.@pipe ...`, I don't know where it goes.

**Comment by fonsp** [comment] 2020-09-11 09:02
Use a `Dict{Symbol,Function}`:

```julia
mock_macros = Dict{Symbol,Function}()

mock_macros[Symbol("@hello")] = (expr) -> ...
...
```
and we call it with:
```julia
expanded = get(mock_macros, found_macro, identity)(expr)
```

**Comment by mcabbott** [comment] 2020-09-11 09:15
Can do. And in principle other packages can push into this Dict... although only if loaded before launching Pluto I guess.

**Comment by fonsp** [comment] 2020-09-11 09:27
It will not be loaded before: when you launch a notebook, Pluto needs to know which order to run it in, _before running the notebook and loading packages_.

**Comment by mcabbott** [comment] 2020-09-13 20:34
OK, I made it a dictionary now, and simplified a bit. See what you think. 

That was poorly phrased about loading, all I meant was that if (say) I want to tell Pluto to ignore some unregistered local `MyPackage.@private`, then instead of having to `] dev Pluto`, I can do `Pluto.MacroZoo.mock_macros[Symbol("@ private")] = ...` before `Pluto.run()`. Which I couldn't do with the list-of-if-statements approach.

Other packages mentioned:

* Vegalite should be easy, one macro `@vlplot` with lots of keyword arguments, and curly braces to remove. https://www.queryverse.org/VegaLite.jl/stable/examples/examples_maps/

* PGFPlotsX has one macro `@pgf Axis({ xlabel = "x", ...` which can use the same function perhaps? https://kristofferc.github.io/PGFPlotsX.jl/dev/examples/gallery.html

* Query.jl has a dozen macros which I think all make functions for use in pipes.  It looks like these could potentially contain references to other objects, but the examples here don't seem to: https://www.queryverse.org/Query.jl/stable/standalonequerycommands/.  @aplavin what thoughts, and do you want to try out what's in #407?

* MATAB uses `@mget x` as assignment.

* UnitfulMoles `@compound x` as assignment

* ModelingToolkit uses `@variables x y z`. Also `@parameters t σ ρ β` and `@variables x(t) y(t) z(t)` and `@derivatives D'~t`says https://github.com/SciML/ModelingToolkit.jl

* JuMP.jl also has `@variable` and `@variables` https://jump.dev/JuMP.jl/v0.21.3/variables/#variables-1 and `@constraint`

* Soss has `@model`, example from top post:
```
m = @model X begin
    β ~ Normal() |> iid(size(X,2))
    y ~ For(eachrow(X)) do x
          Normal(x' * β, 1)
    end
```
But I suspect there are quite a few packages using `@model`, e.g. https://turing.ml/dev/docs/using-turing/advanced . Can these be done together?

**Comment by Pangoraw** [comment] 2021-03-16 17:59
Since macros are non-deterministic, we can't know what code will be executed before a macro call. For this reason, the static analyzers have little to no support for macros. [One common solution](https://github.com/julia-vscode/StaticLint.jl/blob/master/src/macros.jl) is to do what has been done with Pluto for now, which is to write package+macro specific static handlers. 

However, in the case of Pluto, the goals are different than those of static analysis tools because we actually **need** to know which variables/functions will referenced/assigned after a macro call. So instead of doing static analysis which would require a lot of work to deal with package version and to support every package, the idea would be to do the analysis in several steps. 

First we macro expand the macro call, which will give us the expression to be executed. After analyzing this expression, we have the dependencies/children for this cell and can run the cell but by replacing the call with the expanded expression so that there is no surprise with regard to non-deterministic macro expansion. The whole process would look something like this:

1. Gather all macro calls using the traditional ExpressionExplorer
2. Run all imports/using cells on the notebook process
3. Macro expand all the macro calls on the process notebook
4. Re-explore the corresponding cells with the expanded expressions instead of the macro calls.
5. Compute the cell graph as usual
6. Run the cells,  no-need to re-run imports/usings

**Comment by schneiderfelipe** [comment] 2021-04-02 19:58
What about macros like `@md_str`, that interpret a string and build a (deep) `Expr` including interpolated Julia code? I just wrote one (to work with HTML like JSX) but I can't make `@bind` work with it. I'm not sure if that's a common macro pattern, but it's definitely useful.

**Comment by fonsp** [comment] 2021-04-03 07:22
That's not yet possible inside Pluto. This is one reason why HypertextLiteral uses a regular macro instead of a `_str` macro (and also to support nested interpolation).

**Comment by schneiderfelipe** [comment] 2021-04-06 06:23
> That's not yet possible inside Pluto, but it will be an exciting possibility after it is fixed!

Nice! I developed something similar to HypertextLiteral.jl, but it is a standard `@htm_str` macro that behaves very much like `@md_str` in terms of interpolation ([JSX.jl repo](https://github.com/schneiderfelipe/JSX.jl)). The idea was to support a ["component"](https://reactjs.org/docs/components-and-props.html) syntax and to accept arbitrary objects in the structure.

![Captura de tela de 2021-04-06 03-13-44](https://user-images.githubusercontent.com/37125/113666776-28d89a00-9686-11eb-8a05-76098fa5a983.png)

I was hoping to make it work in Pluto.jl just like `@md_str`.

> Also, @schneiderfelipe you should come to PlutoCon next week to discuss JSX! Or send me an email: [fons@plutojl.org](mailto:fons@plutojl.org).

Definitely! 🥳 👍🏽

**Comment by Pangoraw** [comment] 2021-04-07 09:53
> I just wrote one (to work with HTML like JSX), but I can't make @bind work with it

@schneiderfelipe string macros appear as regular macro calls in the expression tree so this should be fixed once #1032 is merged:

![JSX.jl reactive demo](https://user-images.githubusercontent.com/9824244/113846834-2c0f7b00-9797-11eb-87a0-b7e3c1cabe08.gif)

**Comment by zahachtah** [comment] 2021-05-04 15:41
adding an issue with ModelingToolkit.jl that seems to be related. discussed [here](https://discourse.julialang.org/t/issue-with-modelingtoolkit-in-pluto/60517). 

in short:


```
using ModelingToolkit

@parameters t σ ρ β

@variables x(t) y(t) z(t)
```


gives 

**"cannot assign a value to variable workspace3.t from module workspace6"**

**Comment by SyxP** [comment] 2021-07-14 13:08
I believe the following problem is related. Deleting a `@memoize` function (using Memoize or some similar packages.)

The example is as follows:
```
### A Pluto.jl notebook ###
# v0.14.8

using Markdown
using InteractiveUtils

# ╔═╡ dd790891-acb2-459f-b8b6-e1af2e29bf98
using Memoize

# ╔═╡ 3958d75c-38bc-4ea0-ad85-8a11fdd299c2
@memoize function f()
	1
end

# ╔═╡ 8bee9b3b-a664-4293-b762-c90e89530bfa
f()

# ╔═╡ Cell order:
# ╠═dd790891-acb2-459f-b8b6-e1af2e29bf98
# ╠═3958d75c-38bc-4ea0-ad85-8a11fdd299c2
# ╠═8bee9b3b-a664-4293-b762-c90e89530bfa
```

Deleting the second cell still keeps `f()`.

**Closed** 2021-07-27 16:52 UTC
Labels: expression explorer
