### ISSUE TITLE
Export to PDF missing content

### ISSUE THREAD

**Issue by Cyrannosaurus** [fonsp/Pluto.jl#1751] opened 2021-12-08 16:47 UTC
When exporting my Pluto notebooks to PDF, many cells get lost where the PDF transitions from page to page. On top of that, lately, exporting to PDF has left entire pages blank. (Shout out to my TA who informed me and allowed me to resubmit.)

Here is an example notebook:
https://gist.github.com/Cyrannosaurus/dd77c4cb5331634a7a94a8de98bff469

Here is the notebook converted to pdf: 
There may be some differences between the notebook attached and the notebook when I converted it as I was injecting empty cells to try and shift around the contents to not be lost. Some stuff is cut off earlier, but pages 7 & 8 are very obvious.
[hw6_pics.pdf](https://github.com/fonsp/Pluto.jl/files/7677549/hw6_pics.pdf)

**Comment by Cyrannosaurus** [comment] 2021-12-08 16:50
For some reason I can't upload the true pdf. The one I attached is created by taking snips of the file as the original was missing my work. The file is a pdf but GitHub says its extension is not included in the list. Try exporting the .jl file to pdf and the issue should be obvious.

**Comment by fonsp** [comment] 2021-12-08 17:47
Hi @Cyrannosaurus ! We won't be able to run your notebook because it uses local image files: https://gist.github.com/Cyrannosaurus/dd77c4cb5331634a7a94a8de98bff469#file-hw6-jl-L26 

Some tips:
```
┌ Warning: `LocalResource` **will not work** when you share the script/notebook with someone else, _unless they have those resources at exactly the same location on their file system_. 
│ 
│ ## Recommended alternatives (images)
│ 1. Go to [imgur.com](https://imgur.com) and drag&drop the image to the page. Right click on the image, and select "Copy image location". You can now use the image like so: `PlutoUI.Resource("https://i.imgur.com/SAzsMMA.jpg")`.
│ 2. If your notebook is part of a git repository, place the image in the repository and use a relative path: `PlutoUI.LocalResource("../images/cat.jpg")`.
└ @ PlutoUI ~/Documents/PlutoUI.jl/src/Resource.jl:80
```

We also need the original PDF to solve this issue, can you upload it to another service (google drive / dropbox / etc) and share the link here?

**Comment by Cyrannosaurus** [comment] 2021-12-08 18:34
Of course, my bad. Here's a link: https://drive.google.com/file/d/1ju03Iux7w2enaLJ44OcAwoURHX1GwVzx/view?usp=sharing

Let me know if you need any other information.

**Comment by sankayop** [comment] 2021-12-11 12:05
Hy @Cyrannosaurus ,
just to let you know you're not alone :)
Btw, @fonsp, excellent package! Thxs

**Comment by fonsp** [comment] 2021-12-11 17:19
Thanks for the PDF! Can you create a notebook file that will work on my computer (use the tips from https://github.com/fonsp/Pluto.jl/issues/1751#issuecomment-989034920 ) that has this problem?

We won't be able to fix it if we can't reproduce the problem ourselves.

**Comment by sankayop** [comment] 2021-12-11 17:42
Hey @fonsp ,
I don't want to interfere in @Cyrannosaurus chat/work but if necessary, you can find a julia, html and pdf example file here:
https://cloud.adoy.be/s/wHwTBa4mQFkGiM7 (link open till 26/12)

**Comment by fonsp** [comment] 2021-12-11 19:03
Thanks @sankayop , can you put it in a .zip and drag it into this github issue? We probably won't be able to fix it before the 26th because of the holidaus

**Comment by sankayop** [comment] 2021-12-11 19:09
understandable :)
Here you are
[plutoDbg.zip](https://github.com/fonsp/Pluto.jl/files/7697602/plutoDbg.zip)
Early Merry Christmas ;)

**Comment by DhruvaSambrani** [comment] 2022-11-21 18:23
@fonsp what is the update on this issue? facing this right now

**Comment by fonsp** [comment] 2023-01-30 01:05
I can't reproduce this issue on Chrome or Firefox on MacOS today, it might have been fixed in browser updates. It might also have been this firefox bug: #2440 , which is currently being worked on: https://bugzilla.mozilla.org/show_bug.cgi?id=1811548

Closing this for now.

If someone else is able to open the HTML file from the ZIP in https://github.com/fonsp/Pluto.jl/issues/1751#issuecomment-991752576 and then press Ctrl+P to produce the same missing content as seen in the PDF file in the ZIP, let us know your OS and browser version number.

**Closed by fonsp** 2023-01-30 01:05 UTC
