### ISSUE TITLE
Can't open Pluto workbook in browser

### ISSUE THREAD

**Issue by Doubravka** [fonsp/Pluto.jl#607] opened 2020-10-23 15:26 UTC
Worked around by using "CORS everywhere" add-on in Firefox.

![Snímek obrazovky 2020-10-23 171557](https://user-images.githubusercontent.com/48418870/97022049-f0b82180-1553-11eb-9301-f95c93fa7568.png)
![Snímek obrazovky 2020-10-23 171528](https://user-images.githubusercontent.com/48418870/97022076-f7469900-1553-11eb-9026-29dc0291901d.png)

**Comment by fonsp** [comment] 2020-10-23 15:31
What version of firefox do you have?

**Comment by Doubravka** [comment] 2020-10-23 15:38
Hi, I use Firefox 81.0.2.

**Comment by Doubravka** [comment] 2020-10-23 15:45
I've updated for the latest version and it still doesn't work without the
"CORS everywhere" plugin.

**Comment by fonsp** [comment] 2020-10-23 15:49
What extensions do you have installed? Does it also not work in a New Private Window?

**Comment by Doubravka** [comment] 2020-10-23 16:07
Yes, it works in a New Private Window.

**Comment by fonsp** [comment] 2020-10-23 17:34
What extensions do you have installed?

**Comment by pereiragc** [comment] 2020-10-23 22:15
I had the same problem but it was fixed by disabling the DuckDuckGo Privacy Essentials add-on.

**Comment by fonsp** [comment] 2020-10-23 22:45
Can you report this error to the extension?

**Closed by fonsp** 2020-10-23 22:45 UTC

**Comment by fonsp** [comment] 2020-10-28 07:32
This problem is caused by a content-blocking (privacy) extension, and is solved by whitelisting Pluto (e.g. `localhost:1234`) in the extension's settings.

Please also report this error to the browser extension, with enough requests they might want to whitelist Pluto by default.
