### ISSUE TITLE
Inserting period moves the cursor to the beginning of the line on Safari

### ISSUE THREAD

**Issue by samuela** [fonsp/Pluto.jl#1818] opened 2022-01-11 01:48 UTC
There seems to be odd cursor behavior bugs around identifiers (things with underliney links). Adding a period to the end of a line right after an identifier causes the cursor to jump to the beginning of the line (not cell). However this behavior does not occur when there is a space at the beginning of the line. Inserting spaces around identifiers is weird as well, in ways that I do not fully understand (see the second video in particular).

All in all these things severely degrade the user experience, and make typing incredibly frustrating in my experience.

# To report an issue, you need two things:
1. 📹

https://user-images.githubusercontent.com/226872/148866366-cf3f339b-2374-424a-b8c6-d66757cdde48.mov

https://user-images.githubusercontent.com/226872/148866504-52ed2d5e-ad32-4408-a08a-4d20418349ab.mov

2. 📝 https://gist.github.com/samuela/2b2e214015e52a6f0bf23c5f0bbf3470

I'm running Pluto on an x86_64-linux machine but connecting through macOS running Safari Version 15.2 (17612.3.6.1.6).

**Comment by fonsp** [comment] 2022-01-11 12:49
Thanks for the helpful report! I can confirm that this is happening on Pluto 0.17.5 on safari. You can use firefox or chrome while we work on this issue

**Comment by fonsp** [comment] 2022-01-11 12:50
This error gets logged to the console, looks like a CM bug:

<img width="740" alt="Schermafbeelding 2022-01-11 om 13 50 21" src="https://user-images.githubusercontent.com/6933510/148945654-2bb96ee5-fcff-4747-a1ad-48a072611a5b.png">

**Comment by fonsp** [comment] 2022-01-11 12:51
@dralletje What do you think?

**Comment by dralletje** [comment] 2022-01-21 14:21
Just keeping a log for my findings:

It only seems to happen for underlined elements.
It triggers for basically every non-alphanumeric character (Even a space!!).
It happens on safari

**Comment by dralletje** [comment] 2022-01-21 14:23
Oh there is a very much detailed issue already, closing this in favour of that one

**Closed by dralletje** 2022-01-21 14:23 UTC
Labels: bug, frontend, CM6
