### ISSUE TITLE
Stop button of cell only appears when cell is edited

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#121] opened 2020-05-25 06:12 UTC
When executing a cell the stop button only appears when I edit the cell. Although most of the time you probably want to stop it because something needs to be edited, it is irritating that the stop button is not visible when the cell is running and highlighted but only if it is also edited.

Edit: ok, what is actually irritating is that the stop button is there if the cell does not has the keyboard focus but is mouseovered and disappears as soon as I click into the cell, so as soon as it has the keyboard focus. And then reappears when actually changing the cell.

Maybe similar issue: is there a reason why the execution time of a cell is only shown for cells which currently don't have the keyboard focus?

**Comment by karlwessel** [comment] 2020-05-25 06:24
This seems to be a display issue: when I mouse over the place where the stop button should be I get a tooltip saying "run", and when I click at that place the cell is actually stopped.

**Comment by karlwessel** [comment] 2020-05-25 06:32
Steps to reproduce:
1. create a new cell with some long running code like `a = sum(sin(x) for x in 1:1e-11:3)`
2. execute it with ctrl+return
3. stop button is not visible but clickable (and has tooltip "run")
4. create another cell and click into it -> long running cell is not highlighted anymore and stop button is not visible (probably intended and ok)
5. mouseover the long running cell -> the stop button appears again (ok)
6. click into the long running cell -> the stop button disappears but is clickable (not ok)
7. change the long running cell -> the stop button appears

**Comment by fonsp** [comment] 2020-06-03 11:19
I am not able to reproduce this error, but I did find a bug in the interrupt exception showing - this is fixed now. Can you check whether your error is still there after `v0.9.3`?

**Comment by karlwessel** [comment] 2020-06-03 17:55
Hmm, maybe it is a contrast problem. When I reproduce my steps from above now, in the cases where the button was not visible then it is now visible, but very faint.

Is it intended that the stop button gets more faint when the cell gets keyboard focus?

**Comment by fonsp** [comment] 2020-06-09 18:20
Ah I found this problem too, thanks for reporting it!

**Closed** 2020-06-11 23:13 UTC
Labels: almost closed, bug, frontend

**Comment by fonsp** [comment] 2020-06-11 23:16
https://github.com/fonsp/Pluto.jl/commit/e858ef92436f14f4f26e33b8f6970776d0981237
