### ISSUE TITLE
Occasional Hide a Cell Error

### ISSUE THREAD

**Issue by TheCedarPrince** [fonsp/Pluto.jl#138] opened 2020-06-02 15:35 UTC
Hey all,

Every once and a while, when I am working, the hide cell capability fails. I was able to demonstrate this error via the following:

1. Create a new notebook
2. Create only one cell
3. Have it be written in markdown
4. Attempt to hide the code after execution of cell

And when I do that, the markdown code (or any code associated with that cell) is not hidden. The workaround I developed is to simply create more cells when I am working so as to act as a "buffer" against this behavior.

Thanks! I am using Pluto v1.4

**Comment by fonsp** [comment] 2020-06-02 15:38
Can you post a screenshot? What is your Pluto version and your browser version?

**Comment by TheCedarPrince** [comment] 2020-06-02 15:58
Give me a few days to report back on this and I will! :smile:

**Comment by fonsp** [comment] 2020-06-02 16:23
Note that code can not be hidden if it contains unsubmitted code changes - this is intentional.

**Comment by TheCedarPrince** [comment] 2020-06-04 18:42
Hey @fonsp, can you assign this to me? Thanks!

**Comment by fonsp** [comment] 2020-06-12 13:09
I can't reproduce this issue - it was probably fixed by https://github.com/fonsp/Pluto.jl/commit/b3b4b706642bfd5f4f203157ed96601848d49b22

**Closed by fonsp** 2020-06-12 13:09 UTC
Labels: frontend
