### ISSUE TITLE
Disabling a cell with a conflicting definition doesn't resolve the conflict

### ISSUE THREAD

**Issue by derikk** [fonsp/Pluto.jl#2166] opened 2022-06-09 14:49 UTC
When two cells contain conflicting definitions, I expect that disabling one will resolve the conflict. Instead, both cells get grayed out and the conflict remains.

https://user-images.githubusercontent.com/8694764/172874843-db8c9cd2-5b6c-4c84-8547-245d8290bd40.mov

**Comment by Pangoraw** [comment] 2022-06-09 16:34
Closing this because it seems like a duplicate of #1386. There is an initial attempt to solve this in #1859 but I will require a bit more work to handle all cases (indirectly disabled cells)!

**Closed by Pangoraw** 2022-06-09 16:34 UTC
