### ISSUE TITLE
MLJ.@pipeline fails with UndefVarError

### ISSUE THREAD

**Issue by jbrea** [fonsp/Pluto.jl#1658] opened 2021-11-11 14:09 UTC
In julia 1.6.3 the following works in the REPL
```julia
using MLJ
@pipeline(OneHotEncoder)
```

In pluto 0.17.1 this fails with error
```
LoadError: UndefVarError: MLJModelInterface.UnsupervisedComposite not defined
in expression starting at /tmp/macro_failure.jl#==#e4ed3aa6-6544-4e61-b475-52743d6cc606:1

top-level scope@Parameters.jl:611
eval@boot.jl:360[inlined]
eval(::Expr)@PlutoRunner.jl:71
from_network_(::Module, ::Symbol, ::Symbol, ::Expr, ::Bool, ::Dict{Symbol, Any})@from_network.jl:138
pipeline_(::Module, ::Symbol)@pipelines.jl:460
var"@pipeline"(::LineNumberNode, ::Module, ::Vararg{Any, N} where N)@pipelines.jl:541
```

**Comment by roland-KA** [comment] 2021-11-13 14:02
I experienced the same problem using MLJ `@pipeline` macros (see here: [MLJ #865](https://github.com/alan-turing-institute/MLJ.jl/issues/865#issue-1050082290).) In MLJ there will be soon a solution for pipelines which works without macros. 

But my main issue with this problem is, that the code runs perfectly within the REPL, but not in Pluto. So Pluto seems to have a more general problem with processing macros.

I've analyzed the above mentioned error a bit further. Depending on which models you add to the pipeline, the `UndefVarError` differs. It complains about a `MLJModelInterface.UnsupervisedComposite` not defined or a `MLJModelInterface.DeterministicComposite` not defined etc. If you have a look at [MLJBase.jl/src/composition/abstract_types.jl](https://github.com/JuliaAI/MLJBase.jl/blob/a3f54292677008043fb406d15e975cfb18e607af/src/composition/abstract_types.jl) you find there the code where these types are constructed and finally get exported: 

    export MLJType, Model, Surrogate, Composite
    for T in vcat(MMI.ABSTRACT_MODEL_SUBTYPES, COMPOSITE_TYPES, SURROGATE_TYPES)
        @eval(export $T)
    end

It seems to me, that Pluto doesn't get that information correctly.

**Comment by dralletje** [comment] 2021-11-15 20:31
This one stings.. I'll dig into this!

**Comment by Pangoraw** [comment] 2021-11-19 16:36
This may be an issue with MLJ which expects to be called in the `Main` module, to reproduce in the REPL:

```julia
julia> module MyMod
           using MLJ
           
           pipeline = @pipeline(OneHotEncoder)
       end

ERROR: LoadError: UndefVarError: MLJModelInterface.UnsupervisedComposite not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/Parameters/MK0O4/src/Parameters.jl:611
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] eval(x::Expr)
   @ Main.MyMod ./REPL[3]:1
 [4] from_network_(modl::Module, mach_ex::Symbol, modeltype_ex::Symbol, struct_ex::Expr, no_fields::Bool, trait_ex_given_name_ex::Dict{Symbol, Any})
   @ MLJBase ~/.julia/packages/MLJBase/ZzuEC/src/composition/models/from_network.jl:138
 [5] pipeline_(modl::Module, exs::Symbol)
   @ MLJBase ~/.julia/packages/MLJBase/ZzuEC/src/composition/models/pipelines.jl:460
 [6] var"@pipeline"(__source__::LineNumberNode, __module__::Module, exs::Vararg{Any, N} where N)
   @ MLJBase ~/.julia/packages/MLJBase/ZzuEC/src/composition/models/pipelines.jl:541
in expression starting at REPL[3]:4
```

**Comment by dralletje** [comment] 2021-11-19 20:37
That's so odd >_<

**Comment by roland-KA** [comment] 2021-11-22 14:08
Thank you very much @Pangoraw! The hint on how to circumvent the problem works with my notebooks (not only for the `@pipline` macro, but also for `@from_network`).

**Comment by Pangoraw** [comment] 2021-11-22 14:41
The workaround should not be necessary if you use `MLJBase >= 0.18.26` which was released yesterday.

**Comment by roland-KA** [comment] 2021-11-22 18:54
Ah thank's! Indeed, it works without that workaround 😊👍

**Comment by Pangoraw** [comment] 2021-11-24 07:08
Closing since this is fixed in MLJBase. Feel free to reopen if there is still a problem.

**Closed by Pangoraw** 2021-11-24 07:08 UTC
Labels: bug, other packages, macro
