### ISSUE TITLE
Middle mouse button pastes code *everywhere*

### ISSUE THREAD

**Issue by pfitzseb** [fonsp/Pluto.jl#1141] opened 2021-05-04 15:25 UTC
So I tend to spam the middle mouse button to navigate through pages (it brings up a very convenient scroller in Firefox), but that seems to past whatever's in my clipboard into various places: Depending on focus, it ends up in the current cell, as a new cell, or in the "Save notebook..." input:
![image](https://user-images.githubusercontent.com/6735977/117027577-1ee59d80-acfd-11eb-999f-7662f6ca1d22.png)

A cursory search didn't bring up anything that seemed particularly relevant, so maybe it's something code mirror does (or I just can't use GH search well)?

**Comment by fonsp** [comment] 2021-05-04 19:50
(What is MMB?)

**Comment by pankgeorg** [comment] 2021-05-04 21:11
What is your Operating System? Is middle-click paste something Pluto-specific or is your OS setup to send paste events when you click it? (You can test it by pressing the middle key while a text input has focus/in a text editor etc).

If you're on Linux, [this](https://unix.stackexchange.com/questions/24330/how-can-i-turn-off-middle-mouse-button-paste-functionality-in-all-programs) may 'solve' it. If not, let us know!

**Comment by pfitzseb** [comment] 2021-05-04 21:56
Ah, that makes sense -- I though that MMB-to-paste was an application specific thing, not an X feature. That definitely is the reason for what I was seeing.

There's still an issue here though: When no cell is focussed, Ctrl-V pastes the code into a new cell, but *also* into the `Save notebook...` box.

The confusing part about the MMB behaviour (to me) was that a paste event is emitted, directly followed by a click event. That causes newly added cell to lose focus again immedatiely.

**Comment by pankgeorg** [comment] 2021-05-04 22:15
> Ah, that makes sense -- I though that MMB-to-paste was an application specific thing, not an X feature. That definitely is the reason for what I was seeing

😇😇

> There's still an issue here though: When no cell is focussed, Ctrl-V pastes the code into a new cell, but _also_ into the `Save notebook...` box.

Looking into that
 
> The confusing part about the MMB behaviour (to me) was that a paste event is emitted, directly followed by a click event. That causes newly added cell to lose focus again immedatiely.

Unfortunatly the user-agent is obliged to emit a [mousedown event](https://w3c.github.io/uievents/#event-type-mousedown) on any pointer device click; that removes the focus, I think there is not much we can do 😞

**Comment by pankgeorg** [comment] 2021-05-22 21:16
Closing, because I can't progress reproduce the focus box behaviour.

**Closed by pankgeorg** 2021-05-22 21:16 UTC
Labels: bug, frontend
