### ISSUE TITLE
SVector of Vector throws error

### ISSUE THREAD

**Issue by dlfivefifty** [fonsp/Pluto.jl#458] opened 2020-09-19 14:59 UTC
If I have a cell with `SVector(([1,2],))` it throws the following error:
```julia
Failed to show value:
setindex!() with non-isbitstype eltype is not supported by StaticArrays. Consider using SizedArray.
error(::String)@error.jl:33
setindex!@MArray.jl:99[inlined]
copyto!(::StaticArrays.MArray{Tuple{1},Tuple{Int64,Array{Int64,1}},1,1}, ::Base.Iterators.Zip{Tuple{StaticArrays.SOneTo{1},StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1}}})@abstractarray.jl:736
_collect(::UnitRange{Int64}, ::Base.Iterators.Zip{Tuple{StaticArrays.SOneTo{1},StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1}}}, ::Base.HasEltype, ::Base.HasShape{1})@array.jl:630
collect(::Base.Iterators.Zip{Tuple{StaticArrays.SOneTo{1},StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1}}})@array.jl:624
broadcastable(::Base.Iterators.Zip{Tuple{StaticArrays.SOneTo{1},StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1}}})@broadcast.jl:682
broadcasted@broadcast.jl:1261[inlined]
show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("application/vnd.pluto.tree+xml")}, ::StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1})@PlutoRunner.jl:399
#show_richest#16(::Bool, ::typeof(Main.PlutoRunner.show_richest), ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:357
show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:307
#sprint_withreturned#15(::IOContext{Base.PipeEndpoint}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::StaticArrays.SArray{Tuple{1},Array{Int64,1},1,1})@PlutoRunner.jl:279
format_output(::Any)@PlutoRunner.jl:219
formatted_result_of(::Base.UUID, ::Bool)@PlutoRunner.jl:41
top-level scope@none:1
```
This is not an issue in the REPL.

**Comment by Moelf** [comment] 2020-09-23 20:21
looks like this has been fixed by 53e2f3c22bb7554a8422a5f6210b12ecdcdb7683

**Comment by fonsp** [comment] 2020-09-24 08:59
I think both are equally bad 💁

**Comment by OliverEvans96** [comment] 2020-11-18 01:24
This is still an issue in v0.12.10

**Comment by Moelf** [comment] 2020-11-18 02:53
looks like a regression

**Comment by fonsp** [comment] 2020-11-27 18:49
Caused by this bug: https://github.com/JuliaArrays/StaticArrays.jl/issues/855

**Comment by fonsp** [comment] 2020-11-27 19:13
Fixed using a workaround: https://github.com/fonsp/Pluto.jl/pull/725

**Closed** 2020-11-27 19:13 UTC
Labels: backend, bug
