### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by CrazyJannis44** [fonsp/Pluto.jl#1583] opened 2021-10-20 21:50 UTC
Hello,
i just installed Julia and Pluto on localhost to learn Julia and when I use Firefox (also newest version (93)) there's just a blank screen. Here is a screenshot of the browser developer console (it's german)
![screenshot](https://user-images.githubusercontent.com/36644360/138176248-96fb0403-be72-4caf-aad4-5ec8dd41976f.png)
I don't know if this helps but maybe try replicating this (newest versions of Firefox, Julia and Pluto)
Maybe it's just a browser extension, but I don't have any problems on other websites. It works when I use Chrome

**Comment by hydroid7** [comment] 2021-12-15 13:27
I can confirm that in a private window everything works fine.
I also tried to disable uBockOrigin and AdBlockPlus, but it has no effect.

My OS is Ubuntu with Firefox 95.

**Comment by Mattwmaster58** [comment] 2022-04-08 09:40
Tried disabling all my addons as I was also experiencing this issue and it worked. I have 50 addons or so, finding exactly which one will be painful...

Maybe one day I'll write an addon bisector for firefox.

**Comment by CrazyJannis44** [comment] 2022-04-09 22:31
> Tried disabling all my addons as I was also experiencing this issue and it worked. I have 50 addons or so, finding exactly which one will be painful...
> 
> Maybe one day I'll write an addon bisector for firefox.

same but tbh i was too lazy xD

**Comment by honghuzi** [comment] 2022-04-14 06:20
> @honghuzi Can you open a notebook on https://binder.plutojl.org/v0.19.0/ ? (Refresh if you get a "too many users" error)

I'm behind the company firewall, so I cannot access this link.

**Comment by honghuzi** [comment] 2022-04-19 02:31
> @honghuzi Can you open a notebook on https://binder.plutojl.org/v0.19.0/ ? (Refresh if you get a "too many users" error)

could that be a network issue? As in my experience, a jupyter notebook can be opened without network connection. Why would Pluto require network?

**Comment by fonsp** [comment] 2022-04-20 18:58
What Chrome version do you have? It's not a network issue

**Comment by honghuzi** [comment] 2022-04-21 09:03
Same problem on below browsers in windows:

- Chrome 80.0.3987.116 (64-bit)
- Edge 84.0.522.59 (64-bit)

**Comment by fonsp** [comment] 2022-04-22 14:13
@honghuzi Thanks. Unfortunately your Chrome and Edge versions are not supported, these versions are from February 2020. You will need to ask your system administrator to update both browsers.

**Comment by honghuzi** [comment] 2022-05-05 06:33
> @honghuzi Thanks. Unfortunately your Chrome and Edge versions are not supported, these versions are from February 2020. You will need to ask your system administrator to update both browsers.

An updated browser works! Thank you for the advices.

**Comment by fonsp** [comment] 2023-01-30 01:18
This specific issue might have been fixed by https://github.com/fonsp/Pluto.jl/pull/1561, since we no longer need the CDN for core assets (we work offline, getting everything from `localhost`). Extension interference might still be an issue, which is one reason why we are working on https://github.com/JuliaPluto/PlutoDesktop

Closing this because it's not actionable right now, but if people have similar issues, please open a new issue, and post a list of your extensions. Did opening an incognito window without extensions fix your problem? Can you find which (combination of) extensions caused the problem?

**Closed by fonsp** 2023-01-30 01:18 UTC
Labels: HTTP/WS
