### ISSUE TITLE
Code Cell line height

### ISSUE THREAD

**Issue by cenkt** [fonsp/Pluto.jl#545] opened 2020-10-08 09:41 UTC
Hi everyone. Now that Pluto started to use JuliaMono fonts I think the line height in code cells should increase just a little since the new fonts are slimmer and taller.
Do you agree?

**Comment by fonsp** [comment] 2020-10-08 10:02
It would be helpful if you could do the experiment yourself ([edit `editor.css` and refresh](https://github.com/fonsp/Pluto.jl/blob/master/CONTRIBUTING.md)), and post two screenshots.

**Comment by cenkt** [comment] 2020-10-08 10:54
I tried _line-height: 1.45em_; and I think it looks better.

**Code before:**
![pbefore](https://user-images.githubusercontent.com/6926806/95448345-e3a00d80-096b-11eb-9e1f-9a4b4051a4bf.jpg)
**Code after:**
![pafter](https://user-images.githubusercontent.com/6926806/95448405-f9adce00-096b-11eb-8ebb-1a96bc34c5db.jpg)

`pluto-input .CodeMirror,
ul.CodeMirror-hints {
    font-family: JuliaMono, monospace !important;
    font-size: 0.75em;
    line-height: 1.45em;
}
`


**Output before:**
![obefore](https://user-images.githubusercontent.com/6926806/95448456-0f22f800-096c-11eb-9ded-796d93f2ab14.jpg)
**Output after:**
![oafter](https://user-images.githubusercontent.com/6926806/95448497-1944f680-096c-11eb-817d-3c8e240c445a.jpg)

`pluto-output code {
    font-family: JuliaMono, monospace;
    font-size: 0.75rem;
    line-height: 1.5em;}`

**Comment by fonsp** [comment] 2020-10-18 09:44
Can you make a PR?

**Comment by fonsp** [comment] 2020-10-18 09:46
The code line height appears in a lot of places. For example, the cell

```julia
nothing
```

should take up exactly the same amount of vertical space when folded and when unfolded

**Comment by cenkt** [comment] 2020-10-18 19:17
> The code line height appears in a lot of places. For example, the cell
> 
> ```julia
> nothing
> ```
> 
> should take up exactly the same amount of vertical space when folded and when unfolded

**Comment by cenkt** [comment] 2020-10-18 19:18
> Can you make a PR?

I am sorry but what is PR?

**Comment by pranay-simejia** [comment] 2020-11-23 12:20
is this issue solved? I see line-height: 1.45em in editor.css as mentioned above, but the issue is still open.

**Comment by fonsp** [comment] 2020-11-23 18:27
I'm closing this because we need to prioritize

**Closed by fonsp** 2020-11-23 18:27 UTC
Labels: frontend
