### ISSUE TITLE
html download broken in 0.17.1

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#1654] opened 2021-11-09 22:17 UTC
Hi, in 0.17.1 the html download via the notebook menu is broken.
Chrome/linux: proposed filename is `true.html`, when trying to save, chrome says "not allowed"
Firefox/linux:  pops up the modal "open with" dialoge, but ob clicking on `save` does nothing.

Went back to 0.17.0  to proceed, no problems there.

**Comment by fonsp** [comment] 2021-11-09 23:19
Weird, I don't see any [changes between 0.17.0 and 0.17.1](https://github.com/fonsp/Pluto.jl/compare/v0.17.0...v0.17.1) that are related to the HTML export.

I am also not able to reproduce this on MacOS (chrome, firefox, safari), but have not tried on linux.

I found a bug in our code that sets the filename to `true`, this is fixed in #1655, but not sure if that will fix the rest of the issue.

**Comment by fonsp** [comment] 2021-11-15 13:02
Today I was able to reproduce it on Chrome MacOS, and #1655 fixes it!

**Closed** 2021-11-15 13:03 UTC
