### ISSUE TITLE
Incorrect highlighting of (non-)matching `for/end`

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1791] opened 2021-12-28 17:40 UTC
## How to reproduce

Paste this code into a cell:

```julia
let
	sum(
		sum(
			x for x in g
		)
		for x in g
	)
end
```

Now put the cursor _after the last `end`_.

## Result

The last `for` is highlighted as a match:

![](https://user-images.githubusercontent.com/8695383/147592518-9d3319f7-02df-4005-b30f-ade978539065.png)

 ...but it's actually not - the `let` is the correct match.

-------

Looks like the first `for`-loop generator expression (that's Python lingo, not sure what this is called in Julia) is the culprit. If I replace the inner sum with `sum(g)`, everything is highlighted correctly:

```julia
let
	sum(
		sum(g)
		for x in g
	)
end
```

**Comment by pankgeorg** [comment] 2021-12-30 21:27
We use a [light julia parser](https://github.com/lezer-parser/julia) which is, unfortunately not equivalent to the real one.

We'll need to add the special case where the generator parenthesis is omitted when within a function - i.e. this is parsed correctly:
![image](https://user-images.githubusercontent.com/8681967/147789016-44275be2-2d75-4d4f-976c-0075526a010a.png)

**Comment by dralletje** [comment] 2021-12-30 21:35
I'M ON IT @pankgeorg !!!!

**Comment by dralletje** [comment] 2021-12-30 21:36
The problem is the parser didn't understand 
```let <BLANK>
  <expressions>
end```

but it's coming soon! I have a lot of bugs fixed on the julia-lezer side already!
Currently looking at the colors 😏  #1723

**Closed** 2022-01-19 23:16 UTC
Labels: CM6
