### ISSUE TITLE
Pluto dont open notebook

### ISSUE THREAD

**Issue by jcbritobr** [fonsp/Pluto.jl#2593] opened 2023-07-05 12:29 UTC
```
**so - windows 10 x64**
**julia 1.9.1 glib x64**
**browser: Firefox 113 x64**
```
Pluto will not open a notebook if the "notebook=''" parameter is specified.

Steps to reproduce the issue:
1 - Run julia repl
2 - Activate your project
3 - Import Pluto and run Pluto.run(notebook="sample.jl")

![image](https://github.com/fonsp/Pluto.jl/assets/6579862/9297ff3b-5320-4c8c-813c-2d89d8278032)

![image](https://github.com/fonsp/Pluto.jl/assets/6579862/9f2cc96e-247f-4eb2-8070-1f83e0860bee)

Expected behavior - Load the notebook

**Comment by ctrekker** [comment] 2023-07-05 18:08
I'm having trouble reproducing this on Chrome, Firefox, or Edge. When you navigate to `/open` with `secret=...` provided, Pluto.jl should attempt to set a cookie with the same name used for future authenticated requests. The outcome you're experiencing suggests that somehow this cookie is not being set. Make sure you have cookies enabled, and if you do, you could check developer tools to verify that it got set correctly. My guess is that you're on firefox, here's what my developer tools looks like:

![pluto_secret_cookie](https://github.com/fonsp/Pluto.jl/assets/22894011/51f43457-7397-4a38-9d3b-3577c47be2e6)

**Comment by jcbritobr** [comment] 2023-07-05 22:29
Also happens in linux, and the firefox cookie support is configured on default

![image](https://github.com/fonsp/Pluto.jl/assets/6579862/525a944b-9df9-417f-9cfa-3c963eda7106)

![image](https://github.com/fonsp/Pluto.jl/assets/6579862/c5342b7c-3337-4494-993e-ee33f39b853e)

**Comment by jcbritobr** [comment] 2023-07-05 22:55
> I'm having trouble reproducing this on Chrome, Firefox, or Edge. When you navigate to `/open` with `secret=...` provided, Pluto.jl should attempt to set a cookie with the same name used for future authenticated requests. The outcome you're experiencing suggests that somehow this cookie is not being set. Make sure you have cookies enabled, and if you do, you could check developer tools to verify that it got set correctly. My guess is that you're on firefox, here's what my developer tools looks like:
> 
> ![pluto_secret_cookie](https://user-images.githubusercontent.com/22894011/251240003-51f43457-7397-4a38-9d3b-3577c47be2e6.png)

seems same as yours

![image](https://github.com/fonsp/Pluto.jl/assets/6579862/ceb3cc4b-58ff-411c-bd87-c783ce1253b3)

**Comment by fonsp** [comment] 2023-07-06 10:07
Duplicate of #2567, will be fixed in the next Pluto release

**Closed** 2023-07-06 10:36 UTC
