### ISSUE TITLE
Compress Live Docs button so that it can be shown with reduced window size

### ISSUE THREAD

**Issue by rabirabirara** [fonsp/Pluto.jl#447] opened 2020-09-17 19:08 UTC
I like to tile my windows so that I have a notebook in the browser, and a terminal/notepad on the side.  This reduces the screen space granted to Pluto, unfortunately, and with its size, the Live Docs button does not even show up.  I need to maximize the window or drag it out in order to make it appear.

I can't really say that it's a bug, but I at least request that the element to access Live Docs with be made more friendly to various resolutions. 

This is a screenshot of my screen, illustrating the space difference.

![image](https://user-images.githubusercontent.com/59306451/93516045-51619800-f8de-11ea-85e2-34846ec4fe0f.png)

![image](https://user-images.githubusercontent.com/59306451/93516098-676f5880-f8de-11ea-8e3e-890cea6c37ac.png)

**Comment by fonsp** [comment] 2020-09-18 00:09
The problem isn't that the button does not fit - it's that the docs would not fit.

**Comment by rabirabirara** [comment] 2020-09-18 03:04
That's fair.  I assumed that Live Docs worked as an anchored, hovering panel of sorts.  If it needed space, it could cover the text of the notebook when opened; you'd still be able to specify what function's docs to read before opening by clicking (although possibly giving up the ability to change the function while reading the docs).  Sort of like the react-chat-window, or the way message tabs work in Facebook.

I understand if implementing this behavior isn't really worth the effort, but I would hope that eventually there might be accommodation for smaller window sizes.

**Comment by fonsp** [comment] 2020-09-18 19:25
Good point - we could make enable it for small screens, with the purpose of one-time lookups, instead of continuous docs.

We also have the option of scaling down the notebook body to make the docs fit - the question is which of the two should be sacrificed first. There is value in having a fixed maximum notebook width: you can design your output for that width, and it will look the same for everyone.

**Comment by icweaver** [comment] 2020-09-20 08:34
Thanks so much you all for having this discussion =]

I know it's really niche, but I think having something like this would be so useful for vertical monitor setups 🖥️🔃

**Comment by fonsp** [comment] 2020-09-20 11:17
Maybe you could use paint/similar to experiment with this layout - should we overlay the live docs? Should they be less tall when overlayed? Should we compress the notebook to make the docs fit?

**Comment by icweaver** [comment] 2020-09-20 13:48
Ok, wow, I have no idea how you respond to all of these so quickly, it's honestly unreasonable

I don't know if this is what @rabirabirara had in mind, but I was thinking of something like below as an overlay

1) Before opening docs (I zoomed in 150% to mimic what the new layout might look like without the margin on the right reserved for the docs window):
![zoom_150](https://user-images.githubusercontent.com/25312320/93712477-223c6800-fb24-11ea-94fd-608853bc48b6.png)

2) After opening (pardon my amazing GIMP skills):
![zoom_150 docs](https://user-images.githubusercontent.com/25312320/93712490-2e282a00-fb24-11ea-96d2-768387ccded1.png)

Since this fullwidth doc window would fall on top of the notebook cells now, I was wondering if having it automatically pop up as an overlay when your mouse is near the bottom border (or if a keyboard shortcut is pressed) would be a reasonable way to approach this? To avoid having the overlay obscure the syntax your are looking up documentation for, could the overlay pop in from the bottom or top based on if the syntax is located in the opposite part of the current window? If this would be too disruptive to a user's workflow, maybe a manual click on a translucent "Live docs" banner that appears on mouse hover at the bottom could be required instead, like in the original behavior

**Comment by fonsp** [comment] 2020-09-20 14:11
Thanks! The GIMP demo helped my understand you suggestion.

Just writing down another idea: we can also make the Live docs "pop out" into its own window, you can then use your window manager to put it where you like

**Comment by icweaver** [comment] 2020-09-20 14:18
For sure! I could see a separate window as being a bit of a pain point for working on smaller screens, but I think it would still definitely be an ideal way to go if people already have the screen/monitor real estate

**Comment by karlwessel** [comment] 2020-09-23 07:54
I also often have the problem that I can't show any docs when working with Pluto and a Terminal side by side and only have the small laptop screen available. 

For me an partly overlapping doc-pane from the bottom right sounds the most attractive. I can still scroll the code around if something I need to see is behind the pane or just close it for a short time. The width of the pane should be the minimal width Pluto currently thinks acceptable. The height should be the same height as the normal side-by-side pane currently uses.

A separate pop out window would be awful for me. I use a tiling window manager, which would just shrink every other window to make place for the new doc-window. Of course I could then arrange it to a fitting place using the window manager, but that means I have to commit to keeping the doc-window always open since it will forget that position when i close and reopen the doc-window.

**Comment by fonsp** [comment] 2020-10-14 20:34
Try it in 0.12.3

**Comment by fonsp** [comment] 2020-10-14 22:48
The Live Docs are now shown on top of the notebook for any window size >500px. Try it out in `0.12.4`!

**Closed** 2020-10-14 22:49 UTC
Labels: frontend

**Comment by icweaver** [comment] 2020-10-14 23:58
![giphy](https://user-images.githubusercontent.com/25312320/96057711-946c4800-0e57-11eb-90ac-dec09d182a79.gif)

@fonsp does it again!!

**Comment by icweaver** [comment] 2020-10-15 00:01
![Screen Shot 2020-10-14 at 7 55 51 PM](https://user-images.githubusercontent.com/25312320/96057866-e90fc300-0e57-11eb-98a4-ec374b08d3ff.png)

It looks amazing 🌈

**Comment by fonsp** [comment] 2020-10-15 00:06
(Those random walks look extra cool on a dark background, nice!)
