### ISSUE TITLE
Stacktrace - clicking on line reference to jump to cell hides the code if it was previously shown

### ISSUE THREAD

**Issue by BioTurboNick** [fonsp/Pluto.jl#2356] opened 2022-11-04 16:04 UTC
1. Generate a stack trace with an error in another cell.
2. Click on the tag "Other:<linenumber>" to jump there.
3. Scroll back to the stack trace and click again.
4. The offending cell's code is hidden again

v0.19.14

**Comment by fonsp** [comment] 2023-01-30 01:12
I can't reproduce this issue anymore, it might been fixed in v0.19.15 with https://github.com/fonsp/Pluto.jl/commit/4345e127db7be70aca7d8fd59b34de61e8cfa1e5 , this fixed many small codemirror issues. Can you check if you still face the issue, and if so, report your browser and record a video?

**Closed by fonsp** 2023-01-30 01:12 UTC
